# Generated by Django 2.0.1 on 2018-03-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('chofer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('distancia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_so', models.DateField()),
                ('fecha_re', models.DateField()),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField()),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chofer.Chofer')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('origen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Distancia')),
            ],
        ),
    ]
