# Generated by Django 2.0.1 on 2018-03-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(max_length=1),
        ),
    ]
