# Generated by Django 2.0.1 on 2018-03-13 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20180312_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_re',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_so',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
