# Generated by Django 2.0.1 on 2018-03-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20180313_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_so',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
