# Generated by Django 2.0.1 on 2018-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20180404_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, upload_to='EmpleadoFotos/'),
        ),
    ]
