# Generated by Django 2.0.1 on 2018-04-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='ClienteFotos/'),
        ),
    ]
