# Generated by Django 2.0.1 on 2018-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0002_chofer_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='foto',
            field=models.ImageField(blank=True, upload_to='apps/chofer/ChoferFotos/'),
        ),
    ]
