# Generated by Django 2.0.1 on 2018-04-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0004_auto_20180401_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='foto',
            field=models.ImageField(blank=True, upload_to='ChoferFotos/'),
        ),
    ]
